### ISSUE TITLE
Another view of Sim Bias Variance Tradeoff

### ISSUE THREAD

**Issue by hxd1011** [daviddalpiaz/r4sl#10]
First, I really like the Bias Variance Tradeoff Simulation Section!! Thank you very much for making such a great book.

One suggestion from me.

Figure 1 is not very intuitive for me, it shows too many information.
![image](https://user-images.githubusercontent.com/13385855/29086478-c1025c1c-7c40-11e7-9176-ae95b0f01ff4.png)

Alternatively I think this visualization may be better, which only shows the prediction for the x=0.95 cross different model. From 4 sub plots we can clean see, bias and variance.

![image](https://user-images.githubusercontent.com/13385855/29086544-f31dd974-7c40-11e7-8569-fbc2886f3e0d.png)

Here is the code.

	  par(mfrow=c(1,4))
	  plot(rep(0.95,n_sims),predictions[,1],col="red", xlim = c(0.75, 1), ylim = c(0, 1.5))
	  points(x0, f(x0), col = "black", pch = "x", cex = 2)
	  plot(rep(0.95,n_sims),predictions[,2],col="blue", xlim = c(0.75, 1), ylim = c(0, 1.5))
	  points(x0, f(x0), col = "black", pch = "x", cex = 2)
	  plot(rep(0.95,n_sims),predictions[,3],col="green", xlim = c(0.75, 1), ylim = c(0, 1.5))
	  points(x0, f(x0), col = "black", pch = "x", cex = 2)
	  plot(rep(0.95,n_sims),predictions[,4],col="orange", xlim = c(0.75, 1), ylim = c(0, 1.5))
	  points(x0, f(x0), col = "black", pch = "x", cex = 2)

**Comment by daviddalpiaz** [comment]
Thanks for the suggestion! I'll actually be teaching a course on this material this coming semester, so expect updates throughout the fall. This chapter in particular is one I'll definitely be cleaning up.

**Comment by daviddalpiaz** [comment]
Completely rewrote chapter. @hxd1011 if you're willing to provide your name, I'll add you to the acknowledgments. I used your visualization idea.

**Comment by hxd1011** [comment]
Hi, David, Thank you very much for the acknowledgement. My name is Haitao Du. and here is my linkedin profile.

https://www.linkedin.com/in/haitao-du-32a28220/

If you like I am also happy to revise or write some chapter together with you in the future. Thank you again and nice work!.

**Comment by daviddalpiaz** [comment]
Added!
